### ISSUE TITLE
Always run wasm-pack in the crate directory

### ISSUE THREAD

**Issue by fitzgen** [wasm-tool/rust-loader#1]
It should be run in the directory containing `Cargo.toml`. If one tries to have a directory layout like:

```
$ tree -I '**node_modules**'
.
├── index.js
├── rust
│   ├── Cargo.toml
│   ├── src
│   │   └── lib.rs
│   └── wasm-pack.log
└── webpack.config.js
```

and have `index.js` import `rust/src/lib.rs`, then `wasm-pack` is run in the wrong directory. It should be run inside `./rust`.

**Comment by xtuc** [comment]
Good catch thanks!
