### ISSUE TITLE
Use path/to/crate as import path instead of path/to/crate/src/lib.rs

### ISSUE THREAD

**Issue by fitzgen** [wasm-tool/rust-loader#2]
The `test` regexp should become a `test` function that initially checks for the presence of a `Cargo.toml` in the given crate directory. Eventually that check should be replaced with `wasm-pack check` once that command exists.

**Comment by xtuc** [comment]
I've played a bit with that (which I should have done before), here's my observations:
- Importing a virtual file/path is not possible, Webpack will attempt to read it and fail.
    - the `test` function is not invoke before
- If you search `rust loader` on npm, most of them are testing against `.rs`.
- Testing against `/Cargo.toml$/` works, that's probably the way to go?

cc @ashleygwilliams

**Comment by xtuc** [comment]
PR here https://github.com/wasm-tool/rust-loader/pull/3

**Comment by fitzgen** [comment]
Thanks for digging in @xtuc !

> Importing a virtual file/path is not possible, Webpack will attempt to read it and fail. 

Dang.

> If you search rust loader on npm, most of them are testing against .rs.

And that's unfortunate :(

> Testing against /Cargo.toml$/ works, that's probably the way to go?

Yes, this is the next best thing. Maybe to be even more precise, use `/\bCargo.toml$/`.
