### ISSUE TITLE
Show information about compilation (started, progress etc)

### ISSUE THREAD

**Issue by xtuc** [wasm-tool/rust-loader#5]

**Comment by sendilkumarn** [comment]
Cool. So what is the plan here ?

**Comment by xtuc** [comment]
I don't have a plan in mind. Sometimes, especially with the first compilation, it can take a bit of time and the user can't tell what's happening. 

Maybe we need a message saying that the compilation started. What do you think?

**Comment by sendilkumarn** [comment]
That makes sense. I think right now a simple console.log would be sufficient to add in
