### ISSUE TITLE
build command not present in wasm-pack 0.4.2

### ISSUE THREAD

**Issue by robertohuertasm** [wasm-tool/rust-loader#9]
I don't know if this loader is just meant to be used with the next `wasm-pack` version but currently this will not work if someone happens to install `wasm-pack` from `crates.io` as the `build` command is still not present.

If this is something that was intentionally done then feel free to close this issue 😜If not, I can send a PR changing `build` for `init`, which will be still valid in the next version and will go through a deprecation process. We can quickly make the change once `next` version is out and offer support for people not installing `wasm-pack` directly from the repo.

**Comment by xtuc** [comment]
Using the `build` command was indeed intentional. We'll need to wait a new version.
